latest_version() {
    printf '%s\n' "$1"/*(:t) |
        grep -E '^[0-9]+(\.[0-9]+)+$' |
        sort -V |
        tail -n 1
}

export PATH="$HOME/.local/bin:/usr/local/bin:/usr/bin:/bin:$PATH"
export EDITOR="vim"
export LANG=en_ZA.UTF-8

if [[ -d "/usr/local/share/zsh" ]]; then
    fpath=(
        "/usr/local/share/zsh/functions"
        "/usr/local/share/zsh/site-functions"
        $fpath
    )
fi

if [[ -d "$HOME/hep/lhapdf" ]]; then
    LHAPDF_VER=$(latest_version "$HOME/hep/lhapdf")
    if [[ -d "$HOME/hep/lhapdf/$LHAPDF_VER/bin" ]]; then
        export PATH="$PATH:$HOME/hep/lhapdf/$LHAPDF_VER/bin"
        if command -v lhapdf-config &>/dev/null; then
            export LHAPDF_DATA_PATH="$(lhapdf-config --datadir)"
            export LHAPDF_DATADIR="$(lhapdf-config --datadir)"
        fi
    fi
fi

if [[ "$(uname)" == "Darwin" ]]; then
    ARCH="$(uname -m)" 
    
    if [[ "$ARCH" == "arm64" ]]; then
        BREWDIR="/opt/homebrew"
    elif [[ "$ARCH" == "x86_64" ]]; then
        BREWDIR="/usr/local"
    else
        echo "ERROR: ${(%):-%N} :: \`uname -m\` is neither arm64 nor x86_64"
        exit 1
    fi

    if [[ -d "$BREWDIR" ]]; then
        if [[ -d "$BREWDIR/bin" ]]; then
            export PATH="$BREWDIR/bin:$PATH"

            if [[ -x "$BREWDIR/bin/brew" ]]; then
                eval "$("$BREWDIR/bin/brew" shellenv)"
            fi
        fi

        fpath=(
            "$BREWDIR/share/zsh/functions"
            "$BREWDIR/share/zsh/site-functions"
            $fpath
        )
        export HOMEBREW_NO_AUTO_UPDATE=1
    fi

    if [[ -d "/Applications/Wolfram.app/Contents/MacOS" ]]; then
        export PATH="$PATH:/Applications/Wolfram.app/Contents/MacOS"
    fi
fi

